### PR TITLE
feat: Update to AWS SDK v3

### LINKED ISSUE #272: Update AWS SDK to v3?
How about updating AWS SDK to v3?

I suggest doing this with #116 .

I am happy to help. I hope this Action will be active.

### LINKED ISSUE #445: Upgrade AWS SDK from v2 to v3
**Describe the bug**
```
We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
```

When running the action this warning is printed and says that the library will be put into maintenance mode so would be good to ensure this plugin gets sec and other updates and will continue to work in the future.

### PR DESCRIPTION
**Pull request by berviantoleo**
Closes #272 
Closes #445

*Description of changes:*

* Update to AWS SDK v3

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by berviantoleo** [comment]
@Mergifyio queue

**Comment by diversemix** [comment]
Any news on this? Are people living with GA bleeting in the meantime?

**Comment by berviantoleo** [comment]
> Any news on this? Are people living with GA bleeting in the meantime?

Seems, this repo needs new maintainers. There are no updates from maintainers.

**Comment by arjraman** [comment]
Hey @berviantoleo, could you resolve the conflicts and I will look to merge the change.

**Pull request merged**
